import moment from 'moment'
import Head from 'next/head'
import { useEffect } from 'react'

// layouts
import SidebarLayout from '~/layouts/sidebarLayout'

// redux
import { useDispatch, useSelector } from 'react-redux'
import { getById } from '~/redux/callApi/customer'

// components
import Authentication from '~/components/authentication'
import BasicItem, { SidebarData } from '~/components/sidebar/basic'

// hooks
import Section, { SectionTitle } from '~/components/section'
import useAxiosPrivate from '~/hooks/useAxiosPrivate'

function Account() {
    const dispatch = useDispatch()
    const axiosPrivate = useAxiosPrivate()

    const user = useSelector((state) => state.auth.login.currentUser)
    const myInfo = useSelector((state) => state.customer.personal.info)
    const loading = useSelector((state) => state.customer.personal.loading)

    useEffect(() => {
        dispatch(getById({ user, axiosPrivate }))
    }, [dispatch, user, axiosPrivate])

    return (
        <Authentication>
            <Head>
                <title>Thông tin cá nhân | Store Online</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-myInfo.png' />
            </Head>
            <SidebarLayout data={SidebarData} item={BasicItem}>
                <Section>
                    <SectionTitle>Quản lý thông tin hồ sơ của bạn</SectionTitle>
                    {loading
                        ? <div>loading....</div>
                        : (
                            myInfo && <div>
                                <div>Họ và tên: {myInfo.fullName}</div>
                                <div>Địa chỉ: {myInfo.address}</div>
                                <div>Số điện thoại: {myInfo.phone}</div>
                                <div>Tên tài khoản: {myInfo.user.account}</div>
                                <div>Email: {myInfo.user.email}</div>
                                <div>Trạng thái người dùng: {myInfo.user.userStatus.name}</div>
                                <div>Ngày đăng ký: {moment(Date(myInfo.user.createAt)).format('DD-MM-YYYY HH:mm')}</div>
                            </div>
                        )}
                </Section>
            </SidebarLayout>
        </Authentication>
    )
}

export default Account
