import moment from 'moment'
import Head from 'next/head'
import { useEffect } from 'react'

// layouts
import SidebarLayout from '~/layouts/sidebarLayout'

// redux
import { useDispatch, useSelector } from 'react-redux'
import { getById } from '~/redux/callApi/customer'

// components
import Authentication from '~/components/authentication'
import BasicItem, { SidebarData } from '~/components/sidebar/basic'

// hooks
import Section, { SectionTitle } from '~/components/section'
import useAxiosPrivate from '~/hooks/useAxiosPrivate'
import Table, { Cell, Row } from '~/components/table'

function Account() {
    const dispatch = useDispatch()
    const axiosPrivate = useAxiosPrivate()

    const user = useSelector((state) => state.auth.login.currentUser)
    const personal = useSelector((state) => state.customer.personal.info)
    const loading = useSelector((state) => state.customer.personal.loading)

    useEffect(() => {
        dispatch(getById({ user, axiosPrivate }))
    }, [dispatch, user, axiosPrivate])

    return (
        <Authentication>
            <Head>
                <title>Thông tin cá nhân | Store Online</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-myInfo.png' />
            </Head>
            <SidebarLayout data={SidebarData} item={BasicItem}>
                <Section>
                    <SectionTitle>Quản lý thông tin hồ sơ của bạn</SectionTitle>
                    {loading ? (
                        <div>loading....</div>
                    ) : (
                        personal && (
                            <Table>
                                <Row>
                                    <Cell bold>Họ và tên</Cell>
                                    <Cell>{personal.fullName}</Cell>
                                </Row>
                                <Row>
                                    <Cell bold>Địa chỉ</Cell>
                                    <Cell>{personal.address}</Cell>
                                </Row>
                                <Row>
                                    <Cell bold>Số điện thoại</Cell>
                                    <Cell>{personal.phone}</Cell>
                                </Row>
                                <Row>
                                    <Cell bold>Tên tài khoản</Cell>
                                    <Cell>{personal.user.account}</Cell>
                                </Row>
                                <Row>
                                    <Cell bold>Email</Cell>
                                    <Cell>{personal.user.email}</Cell>
                                </Row>
                                <Row>
                                    <Cell bold>Trạng thái người dùng</Cell>
                                    <Cell>{personal.user.userStatus.name}</Cell>
                                </Row>
                                <Row>
                                    <Cell bold>Ngày đăng ký</Cell>
                                    <Cell>
                                        {moment(new Date(personal.user.createdAt)).format(
                                            'DD-MM-YYYY | HH:mm',
                                        )}
                                    </Cell>
                                </Row>
                            </Table>
                        )
                    )}
                </Section>
            </SidebarLayout>
        </Authentication>
    )
}

export default Account
