// reactjs

// nextjs
import Head from 'next/head'
import Link from 'next/link'
import { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import Authentication from '~/components/authentication/admin'
import Button from '~/components/button'
import Section, { SectionContent, SectionTitle } from '~/components/section'
import Table, {
    CategoryItem,
    Cell,
    fieldCategory,
    Row,
    TableBody,
    TableHeader,
} from '~/components/table'

// components

// layouts
import Layout from '~/layouts/admin'
import { getAll } from '~/redux/callApi/category'

// redux

export default function ManageCustomer() {
    const dispatch = useDispatch()
    const categoryList = useSelector((state) => state.category.list.data)
    const loading = useSelector((state) => state.category.list.loading)

    useEffect(() => {
        dispatch(getAll())
    }, [dispatch])

    return (
        <Authentication>
            <Head>
                <title>Quản lý danh mục | Store Online</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-manage-category.png' />
            </Head>
            <Layout>
                <Section>
                    <SectionContent>
                        <Link href='/admin/manage-category/add'>
                            <Button>Thêm danh mục mới</Button>
                        </Link>
                    </SectionContent>
                </Section>
                <Section>
                    <SectionTitle>Danh sách danh mục</SectionTitle>
                    <SectionContent>
                        <Table>
                            <TableHeader data={fieldCategory} />
                            <TableBody>
                                {loading ? (
                                    <Row>
                                        <Cell colSpan={8} center>
                                            loading....
                                        </Cell>
                                    </Row>
                                ) : categoryList?.length <= 0 ? (
                                    <Row>
                                        <Cell colSpan={8} center>
                                            Không có dữ liệu
                                        </Cell>
                                    </Row>
                                ) : (
                                    categoryList?.map((item, i) => {
                                        return (
                                            <CategoryItem
                                                data={item}
                                                key={i}
                                                index={i}
                                            />
                                        )
                                    })
                                )}
                            </TableBody>
                        </Table>
                    </SectionContent>
                </Section>
            </Layout>
        </Authentication>
    )
}
