import Head from "next/head";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import Authentication from "~/components/authentication/admin";
import Button from "~/components/button";
import Form, { FormAction, FormContent } from "~/components/form";
import Input from "~/components/form/input";
import Section, { SectionContent, SectionTitle } from "~/components/section";
import Layout from "~/layouts/admin";
import { getAll } from "~/redux/callApi/category";
import { add } from "~/redux/callApi/product";


export default function Add() {

    const dispatch = useDispatch()
    const categories = useSelector((state) => state.category.list.data)
    const validation = useSelector((state) => state.product.add.error)

    const [state, setState] = useState({})
    const onChangeState = (e) => {
        setState({
            ...state,
            [e.target.name]: e.target.value,
        })
    }

    const handleAddProduct = () => {
        dispatch(add(state))
    }

    useEffect(() => {
        dispatch(getAll())
    }, [dispatch])

    return (
        <Authentication>
            <Head>
                <title>Thêm sản phẩm mới | Store Online</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-manage-product.png' />
            </Head>
            <Layout>
                <Section>
                    <SectionTitle>Thông tin sản phẩm mới</SectionTitle>
                    <SectionContent>
                        {/* {showResult && <FormResult>{message}</FormResult>} */}
                        <Form>
                            <FormContent>
                                <Input
                                    label='Tên sản phẩm'
                                    type='text'
                                    name='name'
                                    onChange={(e) => {
                                        onChangeState(e)
                                    }}
                                    error={validation}
                                />
                                <Input
                                    label='Ảnh đại diện'
                                    type='text'
                                    name='avatar'
                                    onChange={(e) => {
                                        onChangeState(e)
                                    }}
                                    error={validation}
                                />
                                <Input
                                    label='Giá bán'
                                    type='text'
                                    name='price'
                                    onChange={(e) => {
                                        onChangeState(e)
                                    }}
                                    error={validation}
                                />
                                <Input
                                    label='Mô tả'
                                    type='text'
                                    name='description'
                                    onChange={(e) => {
                                        onChangeState(e)
                                    }}
                                    error={validation}
                                />
                                <select name='categoryId' onChange={(e) => {
                                    onChangeState(e)
                                }}>
                                    {categories && categories.map((item, i) => (
                                        <option value={item.id}>{item.name}</option>
                                    ))}
                                </select>
                            </FormContent>
                            <FormAction>
                                <Button type='submit' onClick={handleAddProduct}>
                                    Thêm mới sản phẩm
                                </Button>
                            </FormAction>
                        </Form>
                    </SectionContent>
                </Section>
            </Layout>
        </Authentication>
    )
}