// reactjs

// nextjs
import Head from 'next/head'
import Authentication from '~/components/authentication/admin'
import Section, { SectionTitle } from '~/components/section'
import Table from '~/components/table'

// components

// layouts
import Layout from '~/layouts/admin'

// redux

export default function ManageCustomer() {

    return (
        <Authentication>
            <Head>
                <title>Quản lý sản phẩm | Store Online</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-manage-product.png' />
            </Head>
            <Layout>
                <Section>
                    <SectionTitle>Danh sách sản phẩm</SectionTitle>
                </Section>
            </Layout>
        </Authentication>
    )
}
