import Head from 'next/head'
import Section, { SectionTitle } from '~/components/section'
import Layout from '~/layouts'

function Cart ()
{
    return (
        <>
            <Head>
                <title>Giỏ hàng của bạn | Store Online</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-cart.png' />
            </Head>
            <Layout>
                <Section>
                    <SectionTitle>Quản lý giỏ hàng của bạn</SectionTitle>
                </Section>
                <Section>
                    {/* create cart */ }
                </Section>
            </Layout>
        </>
    )
}

export default Cart
