import Head from "next/head";
import Layout from "../../layouts";

function Cart() {
    return (
        <>
            <Head>
                <title>Giỏ hàng của bạn | Store Online</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/page-cart.png" />
            </Head>
            <Layout>
                Cart
            </Layout>
        </>
    )
}

export default Cart;