import Head from 'next/head'
import CategoryItem from '../../components/list/category'
import List from '../../components/list'
import Section, { SectionContent, SectionTitle } from '../../components/section'
import Layout from '../../layouts'

export default function Home() {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/homeShop.png" />
            </Head>
            <Layout>
                <Section>
                    <SectionTitle>Danh mục</SectionTitle>
                    <SectionContent>
                        <List data={[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]} item={CategoryItem} />
                    </SectionContent>
                </Section>
                <Section>
                    <SectionTitle>Sản phẩm thịnh hành</SectionTitle>
                    <SectionContent>

                    </SectionContent>
                </Section>
                <Section>
                    <SectionTitle>Sản phẩm ưu đãi</SectionTitle>
                    <SectionContent>

                    </SectionContent>
                </Section>
            </Layout >
        </>
    )
}
