// reactjs
import { useEffect, useState } from 'react'

// nextjs
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'

// redux
import { useDispatch, useSelector } from 'react-redux'
import { login } from '~/redux/callApi/auth'

// layouts
import Layout from '~/layouts'

// components
import Form, {
    FormAction,
    FormContent,
    FormFooter,
    FormResult,
    FormTitle,
} from '~/components/form'
import Input from '~/components/form/input'
import Button from '~/components/button'

function Login() {
    const router = useRouter()
    const dispatch = useDispatch()
    const user = useSelector((state) => state.auth.login.currentUser)
    const validation = useSelector((state) => state.auth.login.error)
    const message = useSelector((state) => state.auth.login.message)

    const [state, setState] = useState({})
    const [showResult, setShowResult] = useState(false)

    const onChangeState = (e) => {
        setState({
            ...state,
            [e.target.name]: e.target.value,
        })
    }
    const handleLogin = () => {
        setShowResult(true)
        dispatch(login(state))
    }

    useEffect(() => {
        const navigate = setTimeout(() => {
            if (user && !user.roleId) {
                router.push('/shop')
            }
        }, 750)

        return () => {
            clearTimeout(navigate)
        }
    }, [user, router])

    return (
        <>
            <Head>
                <title>Đăng nhập | Store Online</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-login.png' />
            </Head>
            <Layout>
                <div>
                    {showResult && <FormResult>{message}</FormResult>}
                    <Form>
                        <FormTitle>Đăng nhập</FormTitle>
                        <FormContent>
                            <Input
                                label='Tài khoản'
                                type='text'
                                name='account'
                                placeholder='Enter your account'
                                onChange={(e) => {
                                    onChangeState(e)
                                }}
                                error={validation}
                            />
                            <Input
                                label='Mật khẩu'
                                type='password'
                                name='password'
                                placeholder='Enter your password'
                                onChange={(e) => {
                                    onChangeState(e)
                                }}
                                error={validation}
                            />
                        </FormContent>
                        <FormAction>
                            <Button fill type='submit' onClick={handleLogin}>
                                Login
                            </Button>
                        </FormAction>
                        <FormFooter>
                            <Link href='/shop/register'>Đi đến đăng ký</Link>
                        </FormFooter>
                    </Form>
                </div>
            </Layout>
        </>
    )
}

export default Login
