import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import Authentication from "../../components/authentication";
import Layout from "../../layouts";
import { logout } from "../../redux/callApi/auth";

function Logout() {

    const dispatch = useDispatch()

    const user = useSelector((state) => state.auth.login.currentUser)

    useEffect(() => {
        dispatch(logout(user))
    }, [])

    return (
        <Authentication>
            <Head>
                <title>Log in</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/login.png" />
            </Head>
            <Layout>
                Log out
            </Layout>
        </Authentication>
    )
}

export default Logout;