import { useEffect, useState } from 'react'
import Head from 'next/head'

// components
import Authentication from 'components/authentication'

// layouts
import Layout from 'layouts'

// redux
import { logout } from 'redux/callApi/auth'
import { useDispatch, useSelector } from 'react-redux'

// hooks
import useAxiosPrivate from 'hooks/useAxiosPrivate'
import { FormResult } from 'components/form'

function Logout() {
    const dispatch = useDispatch()
    const axiosPrivate = useAxiosPrivate()
    const user = useSelector((state) => state.auth.login.currentUser)
    const loading = useSelector((state) => state.auth.logout.loading)

    useEffect(() => {
        const dispatchLogout = setTimeout(() => {
            dispatch(logout({ user, axiosPrivate }))
        }, 750)

        return () => {
            clearTimeout(dispatchLogout)
        }
    }, [dispatch, user, axiosPrivate])

    return (
        <Authentication>
            <Head>
                <title>Log in</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/login.png" />
            </Head>
            <Layout>
                <FormResult>
                    Đang đăng xuất....
                </FormResult>
            </Layout>
        </Authentication>
    )
}

export default Logout
