import Head from 'next/head'
import { useEffect } from 'react'

// components
import Authentication from '~/components/authentication'

// layouts
import Layout from '~/layouts'

// redux
import { useDispatch, useSelector } from 'react-redux'
import { logout } from '~/redux/callApi/auth'

// hooks
import { FormResult } from '~/components/form'
import useAxiosPrivate from '~/hooks/useAxiosPrivate'
import Alert from '~/components/alert'
import { toggleAlert } from '~/redux/slices/ui'

function Logout() {
    const dispatch = useDispatch()
    const axiosPrivate = useAxiosPrivate()
    const user = useSelector((state) => state.auth.login.currentUser)

    useEffect(() => {
        const dispatchLogout = setTimeout(() => {
            dispatch(toggleAlert({ status: true }))
            dispatch(logout({ user, axiosPrivate }))
        }, 750)

        return () => {
            clearTimeout(dispatchLogout)
        }
    }, [dispatch, user, axiosPrivate])

    return (
        <Authentication>
            <Head>
                <title>Đăng xuất | Store Online</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-logout.png' />
            </Head>
            <Alert>Đang đăng xuất....</Alert>
            <Layout></Layout>
        </Authentication>
    )
}

export default Logout
