// reactjs
import { useEffect } from "react"

// nextjs
import Head from "next/head"

// redux
import { useDispatch, useSelector } from "react-redux"
import { getAll } from "../../redux/callApi/order"

// layouts
import Layout from "../../layouts"

function Order() {

    const dispatch = useDispatch()


    const getOrders = () => {
        dispatch(getAll())
    }

    const { loading, error, data } = useSelector((state) => state.order)

    console.log(data);

    useEffect(() => {
        getOrders()
    }, [])

    return (
        <>
            <Head>
                <title>Order</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/order.png" />
            </Head>
            <Layout>
                Order:

                {
                    loading
                        ? <div>loading....</div>
                        : data?.data?.map((order, index) => (
                            <div key={index}>{JSON.stringify(order)}</div>
                        ))
                }
            </Layout>
        </>
    )
}

export default Order