// reactjs
import { useEffect } from 'react'

// nextjs
import Head from 'next/head'

// redux
import { useDispatch, useSelector } from 'react-redux'
import { getAll } from '~/redux/callApi/order'

// layouts
import SidebarLayout from '~/layouts/sidebarLayout'

// components
import Authentication from '~/components/authentication'
import BasicItem, { SidebarData } from '~/components/sidebar/basic'

function Order() {
    const dispatch = useDispatch()

    const user = useSelector((state) => state.auth.login.currentUser)
    const list = useSelector((state) => state.order.list.data)

    useEffect(() => {
        dispatch(getAll(user))
    }, [dispatch, user])

    return (
        <Authentication>
            <Head>
                <title>Theo dõi đơn hàng | Store Online</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/page-order.png' />
            </Head>
            <SidebarLayout data={SidebarData} item={BasicItem}>
                <div>
                    <table style={{ border: '1px solid black' }}>
                        <thead>
                            <tr>
                                <th style={{ border: '1px solid black' }}>
                                    Mã đơn hàng
                                </th>
                                <th style={{ border: '1px solid black' }}>
                                    Trạng thái đơn hàng
                                </th>
                                <th style={{ border: '1px solid black' }}>
                                    Ngày đặt hàng
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {list &&
                                list?.map((item, i) => (
                                    <tr key={i}>
                                        <td
                                            style={{
                                                border: '1px solid black',
                                            }}
                                        >
                                            {item.id}
                                        </td>
                                        <td
                                            style={{
                                                border: '1px solid black',
                                            }}
                                        >
                                            {item.orderStatusId}
                                        </td>
                                        <td
                                            style={{
                                                border: '1px solid black',
                                            }}
                                        >
                                            {item.createdAt}
                                        </td>
                                    </tr>
                                ))}
                        </tbody>
                    </table>
                </div>
            </SidebarLayout>
        </Authentication>
    )
}

export default Order
