import Head from "next/head"
import { useEffect, useState } from "react"

import { useDispatch, useSelector } from "react-redux"
import Layout from "../../layouts"
import { setToken } from "../../slices/auth"

function Order() {

    const dispatch = useDispatch()
    const [orders, setOrders] = useState([])

    dispatch(setToken())

    const { token } = useSelector((state) => state.auth)

    const getOrders = async () => {
        try {
            const res = await fetch(`http://localhost:7000/api/customers/1/orders`, {
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': token
                }
            })
            const data = await res.json()
            if (data.affectedRows >= 1) {
                setOrders(data.data)
            }
        } catch (err) { }
    }

    useEffect(() => {
        getOrders()
    }, [])

    return (
        <>
            <Head>
                <title>Order</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/order.png" />
            </Head>
            <Layout>
                Order:
                {
                    orders?.map((order, index) => (
                        <div key={index}>{JSON.stringify(order)}</div>
                    ))
                }
            </Layout>
        </>
    )
}

export default Order