import Head from 'next/head'
import { useEffect, useState } from 'react'
import Layout from '../../layouts'

// redux
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useDispatch, useSelector } from 'react-redux'
import Button from '../../components/button'
import Form, { FormAction, FormContent, FormTitle } from '../../components/form'
import Input from '../../components/form/input'
import { register } from '../../redux/callApi/auth'

function Register() {

    const router = useRouter()
    const dispatch = useDispatch()
    const newUser = useSelector((state) => state.auth.register.newUser)
    const validation = useSelector((state) => state.auth.register.error)
    const message = useSelector((state) => state.auth.register.message)
    const [state, setState] = useState({})

    const onChangeState = (e) => {
        setState({
            ...state,
            [e.target.name]: e.target.value
        })
    }

    const handleRegister = () => {
        dispatch(register(state))
    }

    useEffect(() => {
        if (newUser) {
            router.push('/shop/login')
        }
    }, [dispatch])

    return (
        <>
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/register.png" />
            </Head>
            <Layout>
                <div>
                    <div style={{ color: 'red', minHeight: '1.4rem' }}>{message}</div>
                    <Form>
                        <FormTitle>Đăng ký</FormTitle>
                        <FormContent>
                            <Input
                                label="Họ và tên"
                                type="text"
                                name="fullName"
                                placeholder="Enter your full name"
                                onChange={(e) => { onChangeState(e) }}
                                error={validation || null}
                            />
                            <Input
                                label="Địa chỉ"
                                type="text"
                                name="address"
                                placeholder="Enter your address"
                                onChange={(e) => { onChangeState(e) }}
                                error={validation || null}
                            />
                            <Input
                                label="Số điện thoại"
                                type="text"
                                name="phone"
                                placeholder="Enter your number phone"
                                onChange={(e) => { onChangeState(e) }}
                                error={validation || null}
                            />
                            <Input
                                label="Tài khoản"
                                type="text"
                                name="account"
                                placeholder="Enter your account"
                                onChange={(e) => { onChangeState(e) }}
                                error={validation || null}
                            />
                            <Input
                                label="Mật khẩu"
                                type="password"
                                name="password"
                                placeholder="Enter your password"
                                onChange={(e) => { onChangeState(e) }}
                                error={validation || null}
                            />
                            <Input
                                label="Xác nhận mật khẩu"
                                type="password"
                                name="confirmPassword"
                                placeholder="Enter your confirm password"
                                onChange={(e) => { onChangeState(e) }}
                                error={validation || null}
                            />
                            <Input
                                label="Email"
                                type="text"
                                name="email"
                                placeholder="Enter your email"
                                onChange={(e) => { onChangeState(e) }}
                                error={validation || null}
                            />
                        </FormContent>
                        <FormAction>
                            <Button type="submit" onClick={handleRegister}>Register</Button>
                            <hr />
                            <Link href="/shop/login">Đi đến đăng nhập</Link>
                        </FormAction>
                    </Form>
                </div>
            </Layout>
        </>
    )
}

export default Register