import Head from 'next/head'
import { useState } from 'react'
import Layout from '../../layouts'

// redux
import { useDispatch, useSelector } from 'react-redux'
import { register } from '../../slices/customer'

function Login() {

    const dispatch = useDispatch()
    const { loading, data, error } = useSelector((state) => state.customer)
    const [state, setState] = useState({})

    const onChangeState = (e) => {
        setState({
            ...state,
            [e.target.name]: e.target.value
        })
    }

    const handleRegister = () => {
        dispatch(register(state))
    }

    return (
        <>
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/register.png" />
            </Head>
            <Layout>
                <span><code><hr />{data?.error[0]?.msg}<hr /></code></span>
                <br /><input type="text" placeholder="Enter your account" name="account" onChange={(e) => { onChangeState(e) }} />
                <br /><input type="password" placeholder="Enter your password" name="password" onChange={(e) => { onChangeState(e) }} />
                <br /><input type="password" placeholder="Enter your confirm password" name="confirmPassword" onChange={(e) => { onChangeState(e) }} />
                <br /><input type="text" placeholder="Enter your full name" name="fullName" onChange={(e) => { onChangeState(e) }} />
                <br /><input type="text" placeholder="Enter your address" name="address" onChange={(e) => { onChangeState(e) }} />
                <br /><input type="text" placeholder="Enter your email" name="email" onChange={(e) => { onChangeState(e) }} />
                <br /><input type="text" placeholder="Enter your phone" name="phone" onChange={(e) => { onChangeState(e) }} />
                <br /><button type="submit" onClick={handleRegister}>Register</button>
            </Layout>
        </>
    )
}

export default Login