import Head from 'next/head'
import { useEffect, useState } from 'react'
import Layout from '~/layouts'

// redux
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useDispatch, useSelector } from 'react-redux'
import { register } from '~/redux/callApi/auth'

// components
import Button from '~/components/button'
import Input from '~/components/form/input'
import Form, {
    FormAction,
    FormContent,
    FormFooter,
    FormResult,
    FormTitle,
} from '~/components/form'

function Register() {
    const router = useRouter()
    const dispatch = useDispatch()
    const newUser = useSelector((state) => state.auth.register.newUser)
    const validation = useSelector((state) => state.auth.register.error)
    const message = useSelector((state) => state.auth.register.message)
    const [state, setState] = useState({})
    const [showResult, setShowResult] = useState(false)

    const onChangeState = (e) => {
        setState({
            ...state,
            [e.target.name]: e.target.value,
        })
    }

    const handleRegister = () => {
        dispatch(register(state))
        setShowResult(true)
    }

    useEffect(() => {
        const navigate = setTimeout(() => {
            if (newUser) {
                router.push('/shop/login')
            }
        }, 750)

        return () => {
            clearTimeout(navigate)
        }
    }, [newUser, router, dispatch])

    return (
        <>
            <Head>
                <title>Register</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-register.png' />
            </Head>
            <Layout>
                {showResult && <FormResult>{message}</FormResult>}
                <div>
                    <Form>
                        <FormTitle>Đăng ký</FormTitle>
                        <FormContent>
                            <Input
                                label='Họ và tên'
                                type='text'
                                name='fullName'
                                placeholder='Enter your full name'
                                onChange={(e) => {
                                    onChangeState(e)
                                }}
                                error={validation}
                            />
                            <Input
                                label='Địa chỉ'
                                type='text'
                                name='address'
                                placeholder='Enter your address'
                                onChange={(e) => {
                                    onChangeState(e)
                                }}
                                error={validation}
                            />
                            <Input
                                label='Số điện thoại'
                                type='text'
                                name='phone'
                                placeholder='Enter your number phone'
                                onChange={(e) => {
                                    onChangeState(e)
                                }}
                                error={validation}
                            />
                            <Input
                                label='Tài khoản'
                                type='text'
                                name='user.account'
                                placeholder='Enter your account'
                                onChange={(e) => {
                                    onChangeState(e)
                                }}
                                error={validation}
                            />
                            <Input
                                label='Mật khẩu'
                                type='password'
                                name='user.password'
                                placeholder='Enter your password'
                                onChange={(e) => {
                                    onChangeState(e)
                                }}
                                error={validation}
                            />
                            <Input
                                label='Xác nhận mật khẩu'
                                type='password'
                                name='user.confirmPassword'
                                placeholder='Enter your confirm password'
                                onChange={(e) => {
                                    onChangeState(e)
                                }}
                                error={validation}
                            />
                            <Input
                                label='Email'
                                type='text'
                                name='user.email'
                                placeholder='Enter your email'
                                onChange={(e) => {
                                    onChangeState(e)
                                }}
                                error={validation}
                            />
                        </FormContent>
                        <FormAction>
                            <Button type='submit' onClick={handleRegister}>
                                Register
                            </Button>
                        </FormAction>
                        <FormFooter>
                            <Link href='/shop/login'>Đi đến đăng nhập</Link>
                        </FormFooter>
                    </Form>
                </div>
            </Layout>
        </>
    )
}

export default Register
