import Head from "next/head"
import { useEffect } from "react"
import { useRouter } from "next/router"

// components
import Section, { SectionContent } from "../../../../components/section"

// layouts
import Layout from "../../../../layouts"

// redux
import { useDispatch, useSelector } from "react-redux"
import { getById } from "../../../../redux/callApi/product"

function Detail() {

    const dispatch = useDispatch()
    const loading = useSelector((state) => state.product.detail?.loading)
    const product = useSelector((state) => state.product.detail?.data)

    const getProducts = (id) => {
        dispatch(getById(id))
    }

    const { query } = useRouter()
    useEffect(() => {
        if (query.id) {
            getProducts(query.id)
        }
    }, [query])

    return (
        <>
            <Head>
                <title>{query.name && query.name.split('-').join(' ')} | Store Online</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/page-detail-product.png" />
            </Head>
            <Layout>
                <Section style={{ backgroundImage: 'linear-gradient(135deg, #9796f0 10%, #FBC7D4 100%)' }}>
                    <SectionContent>
                        {loading ? <div>loading...</div> :
                            product && <div>{JSON.stringify(product)}</div>}
                    </SectionContent>
                </Section>
            </Layout>
        </>
    )
}

export default Detail