import Head from 'next/head'
import { useEffect } from 'react'
import { useRouter } from 'next/router'

// components
import Section, { SectionContent } from 'components/section'

// layouts
import Layout from 'layouts'

// redux
import { useDispatch, useSelector } from 'react-redux'
import { getById } from 'redux/callApi/product'

function Detail() {
    const dispatch = useDispatch()
    const loading = useSelector((state) => state.product.detail?.loading)
    const product = useSelector((state) => state.product.detail?.data)

    const { query } = useRouter()
    useEffect(() => {

        const getProducts = (id) => {
            dispatch(getById(id))
        }

        if (query.id) {
            getProducts(query.id)
        }
    }, [query, dispatch])

    return (
        <>
            <Head>
                <title>{query.name && query.name.split('-').join(' ')} | Store Online</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/page-detail-product.png" />
            </Head>
            <Layout>
                <Section>
                    <SectionContent>
                        {loading ? <div>loading...</div> : product && <div>{JSON.stringify(product)}</div>}
                    </SectionContent>
                </Section>
            </Layout>
        </>
    )
}

export default Detail
