// import Head from 'nehead'

// function Index() {
//     return (
//         <>
//             <Head>
//                 <title>Homtitle>
//                 <meta name="description" content="Generated by create next app>
//                 <link rel="icon" hrefshop.png>
//            Head>
//        >
//     )
// }

// export default Index
