// import Head from "next/head"

// function Index() {
//     return (
//         <>
//             <Head>
//                 <title>Home</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <link rel="icon" href="/shop.png" />
//             </Head>
//         </>
//     )
// }

// export default Index