// reactjs

// nextjs
import Head from 'next/head'
import Authentication from '~/components/authentication/admin'

// components

// layouts
import Layout from '~/layouts/admin'

// redux

export default function ManageUser() {

    return (
        <Authentication>
            <Head>
                <title>Quản lý người dùng | Store Online</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-manage-user.png' />
            </Head>
            <Layout>
                Quản lý người dùng
            </Layout>
        </Authentication>
    )
}
