// reactjs

// nextjs
import Head from 'next/head'
import { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import Authentication from '~/components/authentication/admin'
import Section, { SectionContent, SectionTitle } from '~/components/section'
import Table, { fieldUser, TableBody, TableHeader } from '~/components/table'

// components

// layouts
import Layout from '~/layouts/admin'

// redux

export default function ManageUser() {

    // const dispatch = useDispatch()
    // const productList = useSelector((state) => state.user.list.data)
    // const loading = useSelector((state) => state.user.list.loading)

    // useEffect(() => {
    //     dispatch(getAll())
    // }, [dispatch])

    return (
        <Authentication>
            <Head>
                <title>Quản lý người dùng | Store Online</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-manage-user.png' />
            </Head>
            <Layout>
                <Section>
                    <SectionTitle>Danh sách người dùng</SectionTitle>
                    <SectionContent>
                        <Table>
                            <TableHeader data={fieldUser} />
                            <TableBody>
                                {/* {loading
                                    ? <Row><Cell colSpan={8} center>loading....</Cell></Row>
                                    : productList.length <= 0
                                        ? <Row><Cell colSpan={8} center>Không có dữ liệu</Cell></Row>
                                        : productList.map((product, i) => {
                                            return (
                                                <ProductItem data={product} index={i} />
                                            )
                                        })
                                } */}
                            </TableBody>
                        </Table>
                    </SectionContent>
                </Section>
            </Layout>
        </Authentication>
    )
}
