import Head from 'next/head'
import { useEffect } from 'react'
import { useRouter } from 'next/router'

// components
import List from '~/components/list'
import ProductItem from '~/components/list/product'
import Section, { SectionContent } from '~/components/section'

// layouts
import Layout from '~/layouts'

// redux
import { useDispatch, useSelector } from 'react-redux'
import { getProductsByCategory } from '~/redux/callApi/category'

function Detail() {
    const { query } = useRouter()
    const dispatch = useDispatch()
    const loading = useSelector((state) => state.category.productList.loading)
    const products = useSelector((state) => state.category.productList.data)

    useEffect(() => {
        const getProducts = (id) => {
            dispatch(getProductsByCategory(id))
        }

        if (query.id) {
            getProducts(query.id)
        }
    }, [query, dispatch])

    return (
        <>
            <Head>
                <title>
                    {query.name && query.name.split('-').join(' ')} | Store
                    Online
                </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/page-detail-category.png' />
            </Head>
            <Layout>
                <Section>
                    <SectionContent>
                        {loading ? (
                            <div>loading....</div>
                        ) : products.length <= 0 ? (
                            <div>Không có sản phẩm</div>
                        ) : (
                            <List data={products} item={ProductItem} />
                        )}
                    </SectionContent>
                </Section>
            </Layout>
        </>
    )
}

export default Detail
