import Head from "next/head"
import { useEffect } from "react"
import { useRouter } from "next/router"

// components
import Section, { SectionContent } from "../../../../components/section"
import List from "../../../../components/list"

// layouts
import Layout from "../../../../layouts"

// redux
import { useDispatch, useSelector } from "react-redux"
import { getProductsByCategory } from "../../../../redux/callApi/category"
import ProductItem from "../../../../components/list/product"

function Detail() {

    const { query } = useRouter()
    const dispatch = useDispatch()
    const loading = useSelector((state) => state.category.productList.loading)
    const products = useSelector((state) => state.category.productList.data)

    const getProducts = (id) => {
        dispatch(getProductsByCategory(id))
    }

    useEffect(() => {
        if (query.id) {
            getProducts(query.id)
        }
    }, [query])

    return (
        <>
            <Head>
                <title>{query.name && query.name.split('-').join(' ')} | Store Online</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/page-detail-category.png" />
            </Head>
            <Layout>
                <Section style={{ backgroundImage: 'linear-gradient(135deg, #9796f0 10%, #FBC7D4 100%)' }}>
                    <SectionContent>
                        {loading ? <div>loading....</div>
                            : products && <List
                                data={products}
                                item={ProductItem}
                                style={{ gridTemplateColumns: 'repeat(6, 1fr)' }}
                            />}
                    </SectionContent>
                </Section>
            </Layout>
        </>
    )
}

export default Detail