// reactjs

// nextjs
import Head from 'next/head'
import Authentication from '~/components/authentication/admin'

// components

// layouts
import OnlyHeaderLayout from '~/layouts/admin/onlyHeaderLayout'

// redux

export default function Admin() {

    return (
        <Authentication>
            <Head>
                <title>Thông tin cá nhân | Store Online</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-account.png' />
            </Head>
            <OnlyHeaderLayout>
                Thông tin cá nhân
            </OnlyHeaderLayout>
        </Authentication>
    )
}
