// reactjs
import { useEffect, useState } from 'react'

// nextjs
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'

// redux
import { useDispatch, useSelector } from 'react-redux'
import { loginAdmin } from '~/redux/callApi/auth'

// layouts

// components
import Button from '~/components/button'
import Form, {
    FormAction,
    FormContent,
    FormFooter,
    FormResult,
    FormTitle,
} from '~/components/form'
import Input from '~/components/form/input'
import OnlyHeaderLayout from '~/layouts/admin/onlyHeaderLayout'
import { toggleAlert } from '~/redux/slices/ui'
import Alert from '~/components/alert'

function Login() {
    const router = useRouter()
    const dispatch = useDispatch()
    const user = useSelector((state) => state.auth.login.currentUser)
    const validation = useSelector((state) => state.auth.login.error)
    const message = useSelector((state) => state.auth.login.message)

    const [state, setState] = useState({})

    const onChangeState = (e) => {
        setState({
            ...state,
            [e.target.name]: e.target.value,
        })
    }
    const handleLogin = () => {
        dispatch(toggleAlert({ status: true }))
        dispatch(loginAdmin(state))
    }

    useEffect(() => {
        const navigate = setTimeout(() => {
            if (user && user.roleId) {
                router.push('/admin')
            }
        }, 750)

        return () => {
            clearTimeout(navigate)
        }
    }, [user, router])

    return (
        <>
            <Head>
                <title>Log in</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-login.png' />
            </Head>
            <Alert position={['right', 'top']} type={user && 'success' || 'fail'}>{message}</Alert>
            <OnlyHeaderLayout>
                <Form>
                    <FormTitle>Đăng nhập</FormTitle>
                    <FormContent>
                        <Input
                            label='Tài khoản'
                            type='text'
                            name='account'
                            placeholder='Enter your account'
                            onChange={(e) => {
                                onChangeState(e)
                            }}
                            error={validation}
                        />
                        <Input
                            label='Mật khẩu'
                            type='password'
                            name='password'
                            placeholder='Enter your password'
                            onChange={(e) => {
                                onChangeState(e)
                            }}
                            error={validation}
                        />
                    </FormContent>
                    <FormAction>
                        <Button fill type='submit' onClick={handleLogin}>
                            Login
                        </Button>
                    </FormAction>
                </Form>
            </OnlyHeaderLayout>
        </>
    )
}

export default Login
