import Head from 'next/head'
import { useEffect } from 'react'

// components

// layouts

// redux
import { useDispatch, useSelector } from 'react-redux'
import { logout } from '~/redux/callApi/auth'

// hooks
import { FormResult } from '~/components/form'
import useAxiosPrivate from '~/hooks/useAxiosPrivate'
import OnlyHeaderLayout from '~/layouts/admin/onlyHeaderLayout'
import Authentication from '~/components/authentication/admin'

function Logout() {
    const dispatch = useDispatch()
    const axiosPrivate = useAxiosPrivate()
    const user = useSelector((state) => state.auth.login.currentUser)
    const loading = useSelector((state) => state.auth.logout.loading)

    useEffect(() => {
        const dispatchLogout = setTimeout(() => {
            dispatch(logout({ user, axiosPrivate }))
        }, 750)

        return () => {
            clearTimeout(dispatchLogout)
        }
    }, [dispatch, user, axiosPrivate])

    return (
        <Authentication>
            <Head>
                <title>Đăng xuất</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-logout.png' />
            </Head>
            <OnlyHeaderLayout>
                <FormResult>Đang đăng xuất....</FormResult>
            </OnlyHeaderLayout>
        </Authentication>
    )
}

export default Logout
