// reactjs

// nextjs
import Head from 'next/head'
import Authentication from '~/components/authentication/admin'
import Section, { SectionTitle } from '~/components/section'

// components

// layouts
import Layout from '~/layouts/admin'

// redux

export default function Admin() {
    return (
        <Authentication>
            <Head>
                <title>Administrator | Store Online</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-admin.png' />
            </Head>
            <Layout>
                <Section>
                    <SectionTitle>Thống kế</SectionTitle>
                </Section>
            </Layout>
        </Authentication>
    )
}
