import Head from "next/head"
import Link from "next/link"
import { useEffect, useState } from "react"
import { useDispatch, useSelector } from "react-redux"
import Alert from "~/components/alert"
import Authentication from "~/components/authentication/admin"
import Button from "~/components/button"
import Form, { FormAction, FormContent } from "~/components/form"
import Input from "~/components/form/input"
import Section, { SectionContent, SectionTitle } from "~/components/section"
import useAxiosPrivate from "~/hooks/useAxiosPrivate"
import Layout from "~/layouts/admin"
import { add } from "~/redux/callApi/employee"
import { getAll } from "~/redux/callApi/role"
import { toggleAlert } from "~/redux/slices/ui"


export default function Add() {

    const dispatch = useDispatch()
    const axiosPrivate = useAxiosPrivate()
    const user = useSelector((state) => state.auth.login.currentUser)
    const roleList = useSelector((state) => state.role.list.data)
    const data = useSelector((state) => state.employee.add.data)
    const validation = useSelector((state) => state.employee.add.error)
    const message = useSelector((state) => state.employee.add.message)

    const [state, setState] = useState({})

    const onChangeState = (e) => {
        setState({
            ...state,
            [e.target.name]: e.target.value,
        })
    }

    const handleAdd = () => {
        dispatch(toggleAlert({ status: true }))
        dispatch(add({ data: state, axiosPrivate }))
    }

    useEffect(() => {
        dispatch(getAll({ axiosPrivate, user }))
    }, [dispatch, user, axiosPrivate])

    return (
        <Authentication>
            <Head>
                <title>Thêm nhân viên mới | Store Online</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/icon-manage-employee.png' />
            </Head>
            <Alert position={['center', 'top']} type={data && 'success' || 'fail'}>{message}</Alert>
            <Layout>
                <Section>
                    <SectionTitle>Thông tin nhân viên mới</SectionTitle>
                    <SectionContent>
                        <Form>
                            <FormContent>
                                <Input
                                    label='Họ và tên'
                                    type='text'
                                    name='fullName'
                                    onChange={(e) => {
                                        onChangeState(e)
                                    }}
                                    error={validation}
                                />
                                <Input
                                    label='Số điện thoại'
                                    type='text'
                                    name='phone'
                                    onChange={(e) => {
                                        onChangeState(e)
                                    }}
                                    error={validation}
                                />
                                <Input
                                    label='Địa chỉ'
                                    type='text'
                                    name='address'
                                    onChange={(e) => {
                                        onChangeState(e)
                                    }}
                                    error={validation}
                                />
                                <Input
                                    label='Tài khoản'
                                    type='text'
                                    name='account'
                                    onChange={(e) => {
                                        onChangeState(e)
                                    }}
                                    error={validation}
                                />
                                <Input
                                    label='Email'
                                    type='text'
                                    name='email'
                                    onChange={(e) => {
                                        onChangeState(e)
                                    }}
                                    error={validation}
                                />
                                <Input
                                    label='Mật khẩu'
                                    type='password'
                                    name='password'
                                    onChange={(e) => {
                                        onChangeState(e)
                                    }}
                                    error={validation}
                                />
                                <Input
                                    label='Xác nhận mật khẩu'
                                    type='password'
                                    name='confirmPassword'
                                    onChange={(e) => {
                                        onChangeState(e)
                                    }}
                                    error={validation}
                                />
                                <select
                                    name='roleId'
                                    onChange={(e) => {
                                        onChangeState(e)
                                    }}
                                >
                                    {
                                        !roleList
                                            ? <option value={''} defaultValue>
                                                Không có dữ liệu
                                            </option>

                                            : (
                                                <>
                                                    <option value={''} defaultValue>
                                                        Chọn chức vụ
                                                    </option>
                                                    {roleList?.map((item, i) => (
                                                        <option key={i} value={item.id}>
                                                            {item.name}
                                                        </option>
                                                    ))}
                                                </>
                                            )
                                    }
                                </select>
                                <Link href='/admin/manage-category/add'>
                                    <button>Thêm mới</button>
                                </Link>
                            </FormContent>
                            <FormAction>
                                <Button
                                    type='submit'
                                    onClick={handleAdd}
                                >
                                    Thêm mới nhân viên
                                </Button>
                            </FormAction>
                        </Form>
                    </SectionContent>
                </Section>
            </Layout>
        </Authentication>
    )
}
